---
name: Debian package builder for multiple distributions
description: |
  Swiss army knife for projects based on cmake
branding:
  icon: 'compass'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
