#!/bin/bash
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.

set -e -x

apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes "$@"
