---
name: CI
on: [push, pull_request]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/omnilint:latest
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: tag
        name: tag-discovery
        run: |
          tag=latest
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
              tag=${GITHUB_REF#refs/tags/v}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
              tag=${GITHUB_REF#refs/heads/}
          fi
          echo ::set-output name=tag::${tag}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: lpenz/ghaction-cmake:${{ steps.tag.outputs.tag }}
